mistral-7b-sft-beta-re:
  prompt_template: "zephyr-7b-alpha/prompt.txt"
  fn_completions: "vllm_local_completions"
  completions_kwargs:
    model_name: "HuggingFaceH4/mistral-7b-sft-beta"
    model_kwargs:
      torch_dtype: 'bfloat16'
    max_new_tokens: 2048
    temperature: 0.7
    top_p: 1.0
    do_sample: True
  pretty_name: "mistral-7b-sft-beta-re"
