ultra_rdpo_full_eta0.1_beta0.01_stepwise_decay_noise_0:
  prompt_template: "zephyr-7b-alpha/prompt.txt"
  fn_completions: "huggingface_local_completions"
  completions_kwargs:
    model_name: "model/ultra_rdpo_full_eta0.1_beta0.01_stepwise_decay_noise_0"
    model_kwargs:
      torch_dtype: 'bfloat16'
    max_new_tokens: 2048
    temperature: 0.7
    top_p: 1.0
    do_sample: True
  pretty_name: "ultra_rdpo_full_eta0.1_beta0.01_stepwise_decay_noise_0"
