zephyr-7b-gemma_re:
  prompt_template: "zephyr-7b-gemma/prompt.txt"
  fn_completions: "vllm_local_completions"
  completions_kwargs:
    model_name: "HuggingFaceH4/zephyr-7b-gemma-v0.1"
    model_kwargs:
      torch_dtype: 'bfloat16'
    max_new_tokens: 2048
    temperature: 0.7
    top_p: 1.0
  pretty_name: "zephyr-7b-gemma"
